### ISSUE TITLE
I write that the sophisticated processing, perfect tinkering, and artisan's ultrashort skills are not learned on Korean servers.

### ISSUE THREAD

**Issue by gosemaodlzm** [amylase/ffxiv-crafter-rust#26]
It says it's an unlearned word that hasn't been learned yet.

**Comment by Darkttd** [comment]
![image](https://github.com/user-attachments/assets/8bd1a5d7-66fe-4b17-975f-5a2a1e3a909c)

**Comment by amylase** [comment]
@gosemaodlzm Thank you for reporting this. As a global server user, it is not very easy to follow Korean server updates timely. I really appriciate your help!
We have already merged the fix. You should get the fixed version in a few minutes.

**Comment by amylase** [comment]
<img width="729" alt="スクリーンショット 2024-12-08 22 01 54" src="https://github.com/user-attachments/assets/fc39dadf-ca33-4800-96b0-06d9879ff062">

confirmed that new translation is available. Closing this as fixed.
